[["パワー"]]
name = "インクショットダメージ"
effects = [1.0, 1.05, 1.1, 1.15, 1.2, 1.5, 1.55, 1.6, ]
level = 2
to_next_level = 5
[["パワー"]]
name = "爆発ダメージ"
effects = [1.0, 1.3, 1.6, 1.9, 2.1, 3.0, 3.3, ]
level = 1
to_next_level = 3
[["パワー"]]
name = "音波ダメージ"
effects = [1.0, 1.5, 2.0, 2.5, 3.0, ]
level = 1
to_next_level = 3
[["パワー"]]
name = "メイン連射速度"
effects = [
    [1.0, 1.5, 2.0, 2.73, ],
    [1.0, 1.22, 1.41, ], # ローラー
    [1.0, 1.17, 1.31, 1.48, ], # バケツ
]
level = 3
[["パワー"]]
name = "連続ヨコ斬り速度"
effects = [1.0, 1.18, 1.37, 1.62, 2.0, 2.6]
level = 3
[["パワー"]]
name = "スピナー弾数"
effects = [1.0, 1.21, 1.33, ]
level = 1
to_next_level = 3
[["パワー"]]
name = "メインショットダメージ(近)"
effects = [1.0, 1.15, 1.3, 1.45, 1.6, ]
level = 1
to_next_level = 3
[["パワー"]]
name = "メインショットダメージ(遠)"
effects = [1.0, 1.15, 1.3, 1.45, 1.6, ]
level = 1
to_next_level = 3
[["パワー"]]
name = "インクパチパチ"
effects = [1.0, 3.0, 4.0, 5.0, 6.0, ]
level = 1
to_next_level = 3

[["サポート"]]
name = "インク回復速度"
effects = [1.0, 1.25, 1.5, 1.75, ]
level = 2
to_next_level = 5
[["サポート"]]
name = "インク効率(メイン)"
effects = [1.0, 0.8, 0.7, 0.6, 0.5, 0.25]
level = 3
[["サポート"]]
name = "インク効率(サブ)"
effects = [1.0, 0.8, 0.7, 0.6, 0.5, 0.25]
level = 3
[["サポート"]]
name = "撃破インク回復"
effects = [0.0, 0.02, 0.04, ]
level = 1
to_next_level = 3
[["サポート"]]
name = "インクネバネバ"
effects = [0.7, 0.45, ]
level = 2
to_next_level = 5
[["サポート"]]
name = "ノックバック"
effects = [0.0, 1.0, 2.0, 6.0, 10.0, ]
level = 2
to_next_level = 5
[["サポート"]]
name = "爆発ふき飛ばし"
effects = [1.0, 1.17, 1.33, ]
level = 1
to_next_level = 3
[["サポート"]]
name = "ブレ軽減"
effects = [1.0, 0.8, 0.6, ]
level = 2
to_next_level = 5
[["サポート"]]
name = "ホーミング"
effects = [0.0, 0.12, ]
level = 1
to_next_level = 3
[["サポート"]]
name = "チャージ時間"
effects = [1.0, 0.8, 0.6, 0.47, 0.31, 0.03]
level = 1
to_next_level = 3
[["サポート"]]
name = "パージロック"
effects = [false, true]
level = 3
[["サポート"]]
name = "カサ復活時間"
effects = []
level = 1
to_next_level = 3
[["サポート"]]
name = "再チャージ"
effects = [false, true]
level = 3

[["レンジ"]]
name = "メイン射程"
effects = [
    [1.0, 1.25, ],
    [1.0, 1.4, ], # チャージャー
    [1.0, 1.15, 1.2, 1.3, ], # スピナー
]
level = 3
[["レンジ"]]
name = "爆発サイズ"
effects = [1.0, 1.3, 1.45, 1.6, ]
level = 2
to_next_level = 5
[["レンジ"]]
name = "メインショット貫通"
effects = [0, 1, 2, 3, ]
level = 1
to_next_level = 3
[["レンジ"]]
name = "メインショットサイズ"
effects = [1.0, 1.9, 2.35, ]
level = 1
to_next_level = 3
[["レンジ"]]
name = "メインショット塗り"
effects = [1.0, 1.5, 1.8, ]
level = 1
to_next_level = 3
[["レンジ"]]
name = "メイントツゲキ塗り"
effects = [1.0, ]
level = 1
to_next_level = 3
[["レンジ"]]
name = "スペシャル増加量"
effects = [1.0, 1.25, 1.5, ]
level = 2
to_next_level = 5
[["レンジ"]]
name = "塗りドローンゲージ"
effects = [
    [0, 1, 2, 3, 4, 5],
    [0.0, 1.0, 1.5, ], # スピナー
]
level = 1
to_next_level = 3
[["レンジ"]]
name = "塗りラッキーコンボ"
effects = [999999999, 40, ]
level = 1
to_next_level = 3
[["レンジ"]]
name = "おそくした敵ダメージ"
effects = [1.0, 1.3, 1.45, 1.6, 1.7, 2.0]
level = 2
to_next_level = 5

[["ムーブ"]]
name = "イカダッシュ速度"
effects = []
level = 1
to_next_level = 3
[["ムーブ"]]
name = "ヒト移動速度"
effects = [1.0, 1.22, 1.31, 1.4, ]
level = 2
to_next_level = 3
[["ムーブ"]]
name = "塗り進み速度"
effects = [1.0, 1.22, 1.45, 1.6, ]
level = 1
to_next_level = 3
[["ムーブ"]]
name = "???"
effects = []
level = 0
to_next_level = 1
[["ムーブ"]]
name = "チャージキープ"
effects = []
level = 1
to_next_level = 3
[["ムーブ"]]
name = "トツゲキダメージ"
effects = [1.0, 1.33, ]
level = 1
to_next_level = 3
[["ムーブ"]]
name = "トツゲキふき飛ばし"
effects = [1.0, 1.17, 1.33, ]
level = 1
to_next_level = 3
[["ムーブ"]]
name = "イカロールアタック"
effects = [false, true]
level = 3
[["ムーブ"]]
name = "スライドアタック"
effects = [false, true]
level = 3
[["ムーブ"]]
name = "ふみこみアタック"
effects = [false, true]
level = 3
[["ムーブ"]]
name = "移動スペシャル"
effects = []
level = 2
to_next_level = 5
[["ムーブ"]]
name = "移動ドローンゲージ"
effects = []
level = 1
to_next_level = 3
[["ムーブ"]]
name = "移動インク回復"
effects = []
level = 1
to_next_level = 3

[["ラッキー"]]
name = "アーマー確率"
effects = [0.005, 0.01, ]
level = 1
to_next_level = 3
[["ラッキー"]]
name = "インクボトル確率"
effects = [0.01, 0.04, 0.07, 0.1, 0.13, 0.2]
level = 3
[["ラッキー"]]
name = "スペシャルカンヅメ確率"
effects = [0.01, 0.04, 0.07, 0.1, 0.13, 0.2]
level = 3
[["ラッキー"]]
name = "ドローンバッテリー確率"
effects = [0.0, 0.04, 0.07, 0.1, 0.13, 0.2]
level = 3
[["ラッキー"]]
name = "ラッキーボム確率"
effects = [0.0, 0.15, 0.3, 0.45, 0.6, 0.9]
level = 3
[["ラッキー"]]
name = "ディスクパーツ確率"
effects = [0.01, 0.02, 0.03, 0.04, 0.05, 0.06]
level = 3
[["ラッキー"]]
name = "ラッキーコンボ時間"
effects = [3, 5, 7, 9, 11, 20]
level = 2
to_next_level = 5
[["ラッキー"]]
name = "ラッキーコンボ最大数"
effects = [10, 20, 30, 40, ]
level = 2
to_next_level = 5

[["ドローン"]]
name = "ドローンスプラッシュボム"
effects = [999999999, 200, 160, 130, 100, ]
level = 3
[["ドローン"]]
name = "ドローンクイックボム"
effects = [999999999, 180, 150, 120, 90, 60]
level = 3
[["ドローン"]]
name = "ドローンメガホンレーザー"
effects = [999999999, 500, 460, ]
level = 3
[["ドローン"]]
name = "ドローントルネード"
effects = [999999999, 550, 440, 360, 280, 180]
level = 3
[["ドローン"]]
name = "ドローントラップ"
effects = [999999999, 190, 160, 130, 100, 70]
level = 3
[["ドローン"]]
name = "ドローンスプリンクラー"
effects = [999999999, 10, 8, 6, 4, 2]
level = 3
[["ドローン"]]
name = "ドローンアイテム"
effects = [999999999, 600, 500, 400, 300, 200]
level = 3
[["ドローン"]]
name = "時間ドローンゲージ"
effects = [6, 7, 8, 9, 10, 11] # 11?
level = 3
[["ドローン"]]
name = "撃破ドローンゲージ"
effects = [0, 30, 40, 50, 60, 70]
level = 3
