[["パワー"]]
name = "インクショットダメージ"
effects = [1.0, ]
level = 2
to_next_level = 5
[["パワー"]]
name = "爆発ダメージ"
effects = [1.0, ]
level = 1
to_next_level = 3
[["パワー"]]
name = "音波ダメージ"
effects = [1.0, 1.5, 2.0]
level = 1
to_next_level = 3
[["パワー"]]
name = "メイン連射速度"
effects = [1.0, 1.5, 2.0, 2.73, ]
level = 3
[["パワー"]]
name = "連続ヨコ斬り速度"
effects = [1.0, 1.18, ]
level = 0
to_next_level = 1
[["パワー"]]
name = "???"
effects = [1.0, ]
level = 0
to_next_level = 1
[["パワー"]]
name = "メインショットダメージ(近)"
effects = [1.0, ]
level = 1
to_next_level = 3
[["パワー"]]
name = "メインショットダメージ(遠)"
effects = [1.0, ]
level = 1
to_next_level = 3
[["パワー"]]
name = "インクパチパチ"
effects = [1.0, 3.0, ]
level = 1
to_next_level = 3

[["サポート"]]
name = "インク回復速度"
effects = [1.0, 1.25, ]
level = 1
to_next_level = 3
[["サポート"]]
name = "インク効率(メイン)"
effects = [1.0, ]
level = 1
to_next_level = 3
[["サポート"]]
name = "インク効率(サブ)"
effects = [1.0, ]
level = 1
to_next_level = 3
[["サポート"]]
name = "撃破インク回復"
effects = [0.0, 0.02, ]
level = 1
to_next_level = 3
[["サポート"]]
name = "インクネバネバ"
effects = []
level = 2
to_next_level = 5
[["サポート"]]
name = "ノックバック"
effects = []
level = 1
to_next_level = 3
[["サポート"]]
name = "爆発ふき飛ばし"
effects = [1.0, 1.17, 1.33]
level = 1
to_next_level = 3
[["サポート"]]
name = "ブレ軽減"
effects = [1.0, 0.8, 0.6, ]
level = 2
to_next_level = 5
[["サポート"]]
name = "ホーミング"
effects = [0.0, 0.12, ]
level = 1
to_next_level = 3
[["サポート"]]
name = "チャージ時間"
effects = []
level = 1
to_next_level = 3
[["サポート"]]
name = "パージロック"
effects = [false, true]
level = 3
[["サポート"]]
name = "カサ復活時間"
effects = []
level = 1
to_next_level = 3
[["サポート"]]
name = "???"
effects = []
level = 0
to_next_level = 1

[["レンジ"]]
name = "メイン射程"
effects = [1.0, ]
level = 3
[["レンジ"]]
name = "爆発サイズ"
effects = [1.0, 1.3, ]
level = 2
to_next_level = 5
[["レンジ"]]
name = "メインショット貫通"
effects = [0, 1, 2, ]
level = 1
to_next_level = 3
[["レンジ"]]
name = "メインショットサイズ"
effects = [1.0, 1.9, ]
level = 1
to_next_level = 3
[["レンジ"]]
name = "メインショット塗り"
effects = [1.0, ]
level = 1
to_next_level = 3
[["レンジ"]]
name = "メイントツゲキ塗り"
effects = [1.0, ]
level = 1
to_next_level = 3
[["レンジ"]]
name = "スペシャル増加量"
effects = [1.0, 1.25, 1.5, ]
level = 2
to_next_level = 5
[["レンジ"]]
name = "???"
effects = []
level = 0
to_next_level = 1
[["レンジ"]]
name = "塗りラッキーコンボ"
effects = [999999999, 40, ]
level = 1
to_next_level = 3
[["レンジ"]]
name = "おそくした敵ダメージ"
effects = [1.0, 1.3, ]
level = 2
to_next_level = 5

[["ムーブ"]]
name = "イカダッシュ速度"
effects = []
level = 1
to_next_level = 3
[["ムーブ"]]
name = "ヒト移動速度"
effects = [1.0, 1.22, ]
level = 1
to_next_level = 3
[["ムーブ"]]
name = "塗り進み速度"
effects = [1.0, ]
level = 1
to_next_level = 3
[["ムーブ"]]
name = "???"
effects = []
level = 0
to_next_level = 1
[["ムーブ"]]
name = "チャージキープ"
effects = []
level = 1
to_next_level = 3
[["ムーブ"]]
name = "トツゲキダメージ"
effects = [1.0, 1.33, ]
level = 1
to_next_level = 3
[["ムーブ"]]
name = "トツゲキふき飛ばし"
effects = []
level = 1
to_next_level = 3
[["ムーブ"]]
name = "イカロールアタック"
effects = [false, true]
level = 3
[["ムーブ"]]
name = "スライドアタック"
effects = [false, true]
level = 3
[["ムーブ"]]
name = "ふみこみアタック"
effects = [false, true]
level = 3
[["ムーブ"]]
name = "移動スペシャル"
effects = []
level = 2
to_next_level = 5
[["ムーブ"]]
name = "移動ドローンゲージ"
effects = []
level = 1
to_next_level = 3
[["ムーブ"]]
name = "移動インク回復"
effects = []
level = 1
to_next_level = 3

[["ラッキー"]]
name = "アーマー確率"
effects = [0.005, 0.01, ]
level = 0
[["ラッキー"]]
name = "インクボトル確率"
effects = [0.01, 0.04, ]
level = 1
to_next_level = 3
[["ラッキー"]]
name = "スペシャルカンヅメ確率"
effects = []
level = 1
to_next_level = 3
[["ラッキー"]]
name = "ドローンバッテリー確率"
effects = [0.0, 0.04, ]
level = 1
to_next_level = 3
[["ラッキー"]]
name = "ラッキーボム確率"
effects = [0.0, 0.15, 0.3, ]
level = 0
[["ラッキー"]]
name = "ディスクパーツ確率"
effects = [0.01, 0.02, ]
level = 1
to_next_level = 3
[["ラッキー"]]
name = "ラッキーコンボ時間"
effects = [3, 5, ]
level = 0
[["ラッキー"]]
name = "ラッキーコンボ最大数"
effects = [10, 20, ]
level = 1
to_next_level = 3

[["ドローン"]]
name = "ドローンスプラッシュボム"
effects = [999999999, 200, 160, 130, 100, ]
level = 3
[["ドローン"]]
name = "???"
effects = []
level = 0
to_next_level = 1
[["ドローン"]]
name = "ドローンメガホンレーザー"
effects = [999999999, 500, 460, ]
level = 3
[["ドローン"]]
name = "???"
effects = []
level = 0
to_next_level = 1
[["ドローン"]]
name = "???"
effects = []
level = 0
to_next_level = 1
[["ドローン"]]
name = "???"
effects = []
level = 0
to_next_level = 1
[["ドローン"]]
name = "???"
effects = []
level = 0
to_next_level = 1
[["ドローン"]]
name = "時間ドローンゲージ"
effects = [6, 7, 8, 9, 10, ]
level = 3
[["ドローン"]]
name = "???"
effects = []
level = 0
to_next_level = 1
